version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: laravel.sh
      timeout: 400
  AfterInstall:
    - location: config.sh
      timeout: 100
