version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforInstall:
    - location: laravel.sh
      timeout: 100
  AfterInstall:
    - location: config.sh
      timeout: 100
