version: 0.0
os: linux
files:
  - source: /
    destination: /home/
hooks:
  AfterInstall:
    - location: laravel.sh
      timeout: 600
  #ApplicationStart:
   # - location: start.sh
    #  timeout: 100
