version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.4
  pre_build:
    commands:
      - apt-get install php7.4
      # - apt install composer
      - composer global require laravel/installer
  post_build:
    run-as: ubuntu
    commands: 
      - php artisan test
      
artifacts:
  files:
    - '**/*'
