version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.4
  pre_build:
    commands:
      # - apt install composer
      - composer global require laravel/installer
  post_build:
    finally:
      - php artisan test
      
artifacts:
  files:
    - '**/*'
